name: Download Artifact

on:
  workflow_run:
    workflows: ["Create and Upload Artifact"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: downloads

    - name: List files
      run: |
        echo "Directory structure:"
        ls -la
