name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to download artifacts from'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ inputs.run_id }}

    - name: Display content
      run: cat my-files/dummy.txt
