name: Download Artifact

on:
  workflow_run:
    workflows: ["Create and Upload Artifact"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-files
      - name: Display structure of downloaded files
        run: ls -R
