name: Deploy to Staging with Helios

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Which branch to deploy"
        required: true
        type: string
      environment_name:
        description: "Which environment to deploy (environment defined in GitHub)"
        required: true
        type: string
      triggered_by:
        description: "Username that triggered deployment (not required, shown if triggered via GitHub UI, logged if triggered via GitHub app)"
        required: false
        type: string
      commit_sha:
        required: false
        type: string

concurrency: ${{ github.event.inputs.environment_name }}

env:
  CI: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: |
          echo "Branch: ${{ github.event.inputs.branch_name }}"
          sleep 5
          echo "Environment: ${{ github.event.inputs.environment_name }}"
          sleep 5
          echo "Triggered by?: ${{ github.event.inputs.triggered_by }}"


  deploy:
    needs: [ log-inputs ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment_name }}
    steps:
      - name: Echo
        run: |
          echo "Deploying to ${{ github.event.inputs.environment_name }}"
          sleep 10
      - name: Step 2
        run: |
          echo "step 2"
          sleep 10
      - name: Step 3
        run: |
          echo "step 3"
          sleep 10
