name: Upload and Dowload
on:
  workflow_dispatch:

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create dummy file
      run: |
        echo "Hello from GitHub Actions" > dummy.txt
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-files
        path: dummy.txt
        retention-days: 1
        
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: downloaded-files

    - name: List files
      run: |
        echo "Directory structure:"
        ls -la downloaded-files/
