name: Upload Dummy Artifact

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Create dummy WAR file
      run: |
        mkdir -p build/libs
        echo "dummy content" > build/libs/Artemis-1.0.0.war

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artemis.war
        path: build/libs/Artemis-*.war

    - name: List files
      run: ls -l build/libs/
