name: Upload and Dowload
on:
  workflow_dispatch:

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create dummy file
      run: |
        echo "Hello from GitHub Actions" > dummy.txt
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-files
        path: dummy.txt
        
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-files
      - name: Display structure of downloaded files
        run: ls -R
